import type { ComponentCategory } from './types';

export const componentCategories: ComponentCategory[] = [
  {
    title: 'Core Components',
    description: 'Essential building blocks for your application',
    route: 'BaseComponents',
    components: [
      { name: 'BoxView', description: 'Flexible view container with styling props', route: 'BoxViewExample' },
      { name: 'Group', description: 'Horizontal layout with spacing control', route: 'GroupExample' },
      { name: 'Stack', description: 'Vertical layout with spacing control', route: 'StackExample' },
      { name: 'Text', description: 'Typography component with theme support', route: 'TextExample' },
      { name: 'Button', description: 'Full-featured interactive button', route: 'ButtonExample' },
      { name: 'UnstyledButton', description: 'Accessible button without default styles', route: 'UnstyledButtonExample' },
      { name: 'ActionIcon', description: 'Compact icon button for actions', route: 'ActionIconExample' },
      { name: 'Input', description: 'Versatile text input field', route: 'InputExample' },
      { name: 'Loader', description: 'Animated loading indicator', route: 'LoaderExample' },
      { name: 'Icon', description: 'FontAwesome icon component', route: 'IconExample' },
    ],
  },
  {
    title: 'Layout & Typography',
    description: 'Components for structuring content and text',
    route: 'Phase1Components',
    components: [
      { name: 'Center', description: 'Center content both horizontally and vertically', route: 'CenterExample' },
      { name: 'Container', description: 'Responsive container with max-width constraints', route: 'ContainerExample' },
      { name: 'Flex', description: 'Flexible box layout with full control', route: 'FlexExample' },
      { name: 'Space', description: 'Add consistent spacing between elements', route: 'SpaceExample' },
      { name: 'Title', description: 'Semantic heading with size variants', route: 'TitleExample' },
      { name: 'Highlight', description: 'Highlight specific text portions', route: 'HighlightExample' },
      { name: 'Mark', description: 'Marked/highlighted inline text', route: 'MarkExample' },
      { name: 'Code', description: 'Inline code with monospace styling', route: 'CodeExample' },
    ],
  },
  {
    title: 'Feedback & Forms',
    description: 'Visual indicators and form input controls',
    route: 'Phase2Components',
    components: [
      { name: 'Badge', description: 'Status badge with color variants', route: 'BadgeExample' },
      { name: 'Avatar', description: 'User avatar with fallback support', route: 'AvatarExample' },
      { name: 'Paper', description: 'Container with shadow and border radius', route: 'PaperExample' },
      { name: 'Divider', description: 'Visual separator with label support', route: 'DividerExample' },
      { name: 'Progress', description: 'Progress bar with animations', route: 'ProgressExample' },
      { name: 'Skeleton', description: 'Loading placeholder with pulse animation', route: 'SkeletonExample' },
      { name: 'TextInput', description: 'Single-line text input with validation', route: 'TextInputExample' },
      { name: 'Textarea', description: 'Multi-line text input with auto-resize', route: 'TextareaExample' },
      { name: 'PasswordInput', description: 'Secure password input with visibility toggle', route: 'PasswordInputExample' },
      { name: 'Switch', description: 'Toggle switch with labels', route: 'SwitchExample' },
      { name: 'Checkbox', description: 'Checkbox with indeterminate state', route: 'CheckboxExample' },
      { name: 'Radio', description: 'Radio button for exclusive selections', route: 'RadioExample' },
    ],
  },
  {
    title: 'Overlays & Dialogs',
    description: 'Modals, drawers, and overlay components',
    route: 'Phase3Components',
    components: [
      { name: 'Overlay', description: 'Customizable overlay backdrop', route: 'OverlayExample' },
      { name: 'Portal', description: 'Render components outside DOM hierarchy', route: 'PortalExample' },
      { name: 'Modal', description: 'Full-featured modal dialog', route: 'ModalExample' },
      { name: 'Drawer', description: 'Side panel with slide animation', route: 'DrawerExample' },
      { name: 'Dialog', description: 'Lightweight floating dialog', route: 'DialogExample' },
      { name: 'Collapse', description: 'Smooth collapsible content', route: 'CollapseExample' },
      { name: 'Accordion', description: 'Expandable accordion panels', route: 'AccordionExample' },
      { name: 'Spoiler', description: 'Content reveal with show more/less', route: 'SpoilerExample' },
      { name: 'Notification', description: 'Styled notification message', route: 'NotificationExample' },
      { name: 'NumberInput', description: 'Numeric input with increment controls', route: 'NumberInputExample' },
      { name: 'PinInput', description: 'PIN or OTP input with auto-focus', route: 'PinInputExample' },
      { name: 'Chip', description: 'Selectable tag with checkmark', route: 'ChipExample' },
      { name: 'NativeSelect', description: 'Platform-native dropdown select', route: 'NativeSelectExample' },
    ],
  },
  {
    title: 'Data Display',
    description: 'Tables, lists, and complex data presentation',
    route: 'Phase4Components',
    components: [
      { name: 'Slider', description: 'Range slider with marks and labels', route: 'SliderExample' },
      { name: 'Rating', description: 'Interactive star rating', route: 'RatingExample' },
      { name: 'Stepper', description: 'Multi-step form navigation', route: 'StepperExample' },
      { name: 'SegmentedControl', description: 'Segmented button group selector', route: 'SegmentedControlExample' },
      { name: 'Pagination', description: 'Page navigation with controls', route: 'PaginationExample' },
      { name: 'Card', description: 'Content card with sections', route: 'CardExample' },
      { name: 'Timeline', description: 'Vertical timeline with items', route: 'TimelineExample' },
      { name: 'Table', description: 'Styled data table', route: 'TableExample' },
      { name: 'List', description: 'Ordered and unordered lists', route: 'ListExample' },
    ],
  },
  {
    title: 'Media & Utilities',
    description: 'Images, icons, and utility components',
    route: 'Phase5Components',
    components: [
      { name: 'Image', description: 'Responsive image with placeholder', route: 'ImageExample' },
      { name: 'BackgroundImage', description: 'Container with background image', route: 'BackgroundImageExample' },
      { name: 'ThemeIcon', description: 'Icon with themed background', route: 'ThemeIconExample' },
      { name: 'ColorSwatch', description: 'Color preview swatch', route: 'ColorSwatchExample' },
      { name: 'Transition', description: 'Animated mount/unmount transitions', route: 'TransitionExample' },
      { name: 'CloseButton', description: 'Universal close button', route: 'CloseButtonExample' },
      { name: 'CopyButton', description: 'Copy text to clipboard', route: 'CopyButtonExample' },
      { name: 'Burger', description: 'Animated hamburger menu icon', route: 'BurgerExample' },
    ],
  },
  {
    title: 'Navigation & Advanced',
    description: 'Navigation, menus, and advanced features',
    route: 'Phase6Components',
    components: [
      { name: 'Anchor', description: 'Styled link component', route: 'AnchorExample' },
      { name: 'Kbd', description: 'Keyboard shortcut display', route: 'KbdExample' },
      { name: 'Indicator', description: 'Notification dot indicator', route: 'IndicatorExample' },
      { name: 'Grid', description: 'Flexible CSS Grid layout', route: 'GridExample' },
      { name: 'SimpleGrid', description: 'Auto-responsive grid layout', route: 'SimpleGridExample' },
      { name: 'AspectRatio', description: 'Maintain fixed aspect ratio', route: 'AspectRatioExample' },
      { name: 'MediaQuery', description: 'Responsive visibility control', route: 'MediaQueryExample' },
      { name: 'Blockquote', description: 'Styled quotation block', route: 'BlockquoteExample' },
      { name: 'Breadcrumbs', description: 'Navigation breadcrumb trail', route: 'BreadcrumbsExample' },
      { name: 'NavLink', description: 'Navigation link with active state', route: 'NavLinkExample' },
      { name: 'LoadingOverlay', description: 'Full-screen loading state', route: 'LoadingOverlayExample' },
      { name: 'Tooltip', description: 'Contextual tooltip popup', route: 'TooltipExample' },
      { name: 'Popover', description: 'Rich content popover', route: 'PopoverExample' },
      { name: 'Menu', description: 'Dropdown menu with items', route: 'MenuExample' },
      { name: 'Select', description: 'Searchable select dropdown', route: 'SelectExample' },
      { name: 'MultiSelect', description: 'Multi-option select with tags', route: 'MultiSelectExample' },
      { name: 'RingProgress', description: 'Circular progress indicator', route: 'RingProgressExample' },
      { name: 'TransferList', description: 'Dual-list selection transfer', route: 'TransferListExample' },
    ],
  },
];
