import type { ComponentCategory } from './types';

export const componentCategories: ComponentCategory[] = [
  {
    title: 'Base Components',
    description: 'Foundation components that existed before the migration',
    route: 'BaseComponents',
    components: [
      { name: 'BoxView', description: 'Basic view container with styling', route: 'BoxViewExample' },
      { name: 'Group', description: 'Horizontal layout group', route: 'GroupExample' },
      { name: 'Stack', description: 'Vertical layout stack', route: 'StackExample' },
      { name: 'Text', description: 'Text component with theming', route: 'TextExample' },
      { name: 'Button', description: 'Interactive button component', route: 'ButtonExample' },
      { name: 'UnstyledButton', description: 'Button without default styles', route: 'UnstyledButtonExample' },
      { name: 'ActionIcon', description: 'Icon button component', route: 'ActionIconExample' },
      { name: 'Input', description: 'Basic input field', route: 'InputExample' },
      { name: 'Loader', description: 'Loading spinner component', route: 'LoaderExample' },
    ],
  },
  {
    title: 'Phase 1: Foundation Components',
    description: 'Layout and text foundation components',
    route: 'Phase1Components',
    components: [
      { name: 'Center', description: 'Center children horizontally and vertically', route: 'CenterExample' },
      { name: 'Container', description: 'Constrained width container', route: 'ContainerExample' },
      { name: 'Flex', description: 'Flexible box layout', route: 'FlexExample' },
      { name: 'Space', description: 'Add spacing between elements', route: 'SpaceExample' },
      { name: 'Title', description: 'Heading text component', route: 'TitleExample' },
      { name: 'Highlight', description: 'Highlight text portions', route: 'HighlightExample' },
      { name: 'Mark', description: 'Mark/highlight inline text', route: 'MarkExample' },
      { name: 'Code', description: 'Inline code text', route: 'CodeExample' },
    ],
  },
  {
    title: 'Phase 2: Essential Components',
    description: 'Visual feedback and form input components',
    route: 'Phase2Components',
    components: [
      { name: 'Badge', description: 'Small status badge', route: 'BadgeExample' },
      { name: 'Avatar', description: 'User avatar component', route: 'AvatarExample' },
      { name: 'Paper', description: 'Paper background container', route: 'PaperExample' },
      { name: 'Divider', description: 'Visual divider line', route: 'DividerExample' },
      { name: 'Progress', description: 'Progress bar indicator', route: 'ProgressExample' },
      { name: 'Skeleton', description: 'Loading skeleton placeholder', route: 'SkeletonExample' },
      { name: 'TextInput', description: 'Text input field', route: 'TextInputExample' },
      { name: 'Textarea', description: 'Multi-line text input', route: 'TextareaExample' },
      { name: 'PasswordInput', description: 'Password input field', route: 'PasswordInputExample' },
      { name: 'Switch', description: 'Toggle switch control', route: 'SwitchExample' },
      { name: 'Checkbox', description: 'Checkbox control', route: 'CheckboxExample' },
      { name: 'Radio', description: 'Radio button control', route: 'RadioExample' },
    ],
  },
  {
    title: 'Phase 3: Advanced UI Components',
    description: 'Interactive overlays and advanced form components',
    route: 'Phase3Components',
    components: [
      { name: 'Overlay', description: 'Overlay background layer', route: 'OverlayExample' },
      { name: 'Portal', description: 'Render component in portal', route: 'PortalExample' },
      { name: 'Modal', description: 'Modal dialog', route: 'ModalExample' },
      { name: 'Drawer', description: 'Side drawer panel', route: 'DrawerExample' },
      { name: 'Dialog', description: 'Simple dialog component', route: 'DialogExample' },
      { name: 'Collapse', description: 'Collapsible content', route: 'CollapseExample' },
      { name: 'Accordion', description: 'Accordion/expandable list', route: 'AccordionExample' },
      { name: 'Spoiler', description: 'Expandable spoiler content', route: 'SpoilerExample' },
      { name: 'Notification', description: 'Notification message', route: 'NotificationExample' },
      { name: 'NumberInput', description: 'Number input with controls', route: 'NumberInputExample' },
      { name: 'PinInput', description: 'PIN/OTP input field', route: 'PinInputExample' },
      { name: 'Chip', description: 'Selectable chip component', route: 'ChipExample' },
      { name: 'NativeSelect', description: 'Native dropdown select', route: 'NativeSelectExample' },
    ],
  },
  {
    title: 'Phase 4: Complex Features',
    description: 'Advanced interactions and data display',
    route: 'Phase4Components',
    components: [
      { name: 'Slider', description: 'Slider control', route: 'SliderExample' },
      { name: 'Rating', description: 'Star rating component', route: 'RatingExample' },
      { name: 'Stepper', description: 'Step-by-step navigation', route: 'StepperExample' },
      { name: 'SegmentedControl', description: 'Segmented button group', route: 'SegmentedControlExample' },
      { name: 'Pagination', description: 'Page navigation', route: 'PaginationExample' },
      { name: 'Card', description: 'Card container', route: 'CardExample' },
      { name: 'Timeline', description: 'Timeline display', route: 'TimelineExample' },
      { name: 'Table', description: 'Data table', route: 'TableExample' },
      { name: 'List', description: 'Styled list component', route: 'ListExample' },
    ],
  },
  {
    title: 'Phase 5: Specialized Components',
    description: 'Images, media, and utility components',
    route: 'Phase5Components',
    components: [
      { name: 'Image', description: 'Image component', route: 'ImageExample' },
      { name: 'BackgroundImage', description: 'Background image container', route: 'BackgroundImageExample' },
      { name: 'ThemeIcon', description: 'Themed icon container', route: 'ThemeIconExample' },
      { name: 'ColorSwatch', description: 'Color swatch display', route: 'ColorSwatchExample' },
      { name: 'Transition', description: 'Animated transitions', route: 'TransitionExample' },
      { name: 'CloseButton', description: 'Close button', route: 'CloseButtonExample' },
      { name: 'CopyButton', description: 'Copy to clipboard button', route: 'CopyButtonExample' },
      { name: 'Burger', description: 'Hamburger menu button', route: 'BurgerExample' },
    ],
  },
  {
    title: 'Phase 6: Advanced/Complex Components',
    description: 'Advanced layout, navigation, and form components',
    route: 'Phase6Components',
    components: [
      { name: 'Anchor', description: 'Link/anchor component', route: 'AnchorExample' },
      { name: 'Kbd', description: 'Keyboard key display', route: 'KbdExample' },
      { name: 'Indicator', description: 'Notification indicator', route: 'IndicatorExample' },
      { name: 'Grid', description: 'CSS Grid layout', route: 'GridExample' },
      { name: 'SimpleGrid', description: 'Simple responsive grid', route: 'SimpleGridExample' },
      { name: 'AspectRatio', description: 'Fixed aspect ratio container', route: 'AspectRatioExample' },
      { name: 'MediaQuery', description: 'Responsive media query', route: 'MediaQueryExample' },
      { name: 'Blockquote', description: 'Blockquote text', route: 'BlockquoteExample' },
      { name: 'Breadcrumbs', description: 'Breadcrumb navigation', route: 'BreadcrumbsExample' },
      { name: 'NavLink', description: 'Navigation link', route: 'NavLinkExample' },
      { name: 'LoadingOverlay', description: 'Loading overlay', route: 'LoadingOverlayExample' },
      { name: 'Tooltip', description: 'Tooltip popup', route: 'TooltipExample' },
      { name: 'Popover', description: 'Popover dropdown', route: 'PopoverExample' },
      { name: 'Menu', description: 'Dropdown menu', route: 'MenuExample' },
      { name: 'Select', description: 'Custom select dropdown', route: 'SelectExample' },
      { name: 'MultiSelect', description: 'Multi-select dropdown', route: 'MultiSelectExample' },
      { name: 'RingProgress', description: 'Ring progress indicator', route: 'RingProgressExample' },
      { name: 'TransferList', description: 'Transfer list component', route: 'TransferListExample' },
    ],
  },
];
